### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by JannePalmen** [klausweiss/todo.txt-hiding#1]
Cannot download hiding. Following error:

```
$ git clone git@github.com:klausweiss/todo.txt-hiding.git hiding
Klonar till "hiding"...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by klausweiss** [comment]
Thank you! The issue was with the README. You should use https instead of ssh:
```
git clone https://github.com/klausweiss/todo.txt-hiding.git hiding
```

**Comment by JannePalmen** [comment]
Thank you. Installation worked perfect.
But a new problem occurred.
When executing the command:
` ~ $ ./todo.sh hiding @mycontext`
it results in:
`/bin/sh: 1: todo.sh: not found`

Any idea what the problem might be?

**Comment by klausweiss** [comment]
I'm glad to hear that. Have you installed [todo.sh](https://github.com/todotxt/todo.txt-cli) itself? Had it worked before plugin installation?
